# fly.toml app configuration file generated for srhqmp-library on 2024-06-01T22:02:06+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'srhqmp-library'
primary_region = 'sin'

[build]

[env]
  PORT = "4000"
  
[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
